### ISSUE TITLE
 Warning: Redis::pconnect(): connect() failed

### ISSUE THREAD

**Issue by Evilran** [ZpGuo/zPhal#2]
您好，我在配置好dockerfiles后启动docker，发现Redis连接错误了。

Warning: Redis::pconnect(): connect() failed: Connection refused in /data/www/zPhal/app/common/library/Options/Redis.php on line 56
Could not connect to the Redisd server 127.0.0.1:6379
#0 [internal function]: Phalcon\Cache\Backend\Redis->_connect()
#1 /data/www/zPhal/app/common/library/Options/Redis.php(56): Phalcon\Cache\Backend\Redis->exists('_zphal_option')
#2 /data/www/zPhal/app/common/library/Options/Redis.php(42): ZPhal\Library\Options\Redis->init()
#3 /data/www/zPhal/app/common/providers/Option/ServiceProvider.php(34): ZPhal\Library\Options\Redis->__construct()
#4 [internal function]: ZPhal\Providers\Option\ServiceProvider->ZPhal\Providers\Option\{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('option', NULL)
#7 [internal function]: Phalcon\Di->getShared('option')
#8 /data/www/zPhal/app/modules/frontend/controllers/ControllerBase.php(12): Phalcon\Di\Injectable->__get('option')
#9 [internal function]: ZPhal\Modules\Frontend\Controllers\ControllerBase->onConstruct()
#10 [internal function]: Phalcon\Mvc\Controller->__construct()
#11 [internal function]: Phalcon\Di->get('ZPhal\\Modules\\F...', NULL)
#12 [internal function]: Phalcon\Di->getShared('ZPhal\\Modules\\F...')
#13 [internal function]: Phalcon\Dispatcher->dispatch()
#14 /data/www/zPhal/bootstrap/bootstrap.php(82): Phalcon\Mvc\Application->handle()
#15 /data/www/zPhal/bootstrap/autoloader.php(39): require('/data/www/zPhal...')
#16 /data/www/zPhal/public/index.php(18): require('/data/www/zPhal...')
#17 {main}

**Comment by goozp** [comment]
> Could not connect to the Redisd server 127.0.0.1:6379

redis是怎么配置的。
env 文件的 REDIS_HOST 配置成docker容器的host
比如REDIS_HOST=redis-db

如果用docker跑，redis单独是一个容器的话，redis 的host就不是127.0.0.1，不然会找容器内部的redis服务去了

**Comment by Evilran** [comment]
可是我用 redis-cli -h 127.0.0.1 -p 6379 也是通的，要在哪里设置env呢？因为我是直接按照dockerfile pull的镜像。

docker inspect 得到：
            "Ports": {
                "6379/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "6379"
                    }
                ]

**Comment by goozp** [comment]
是在宿主机执行redis-cli?
如果你是docker exec进入redis容器后执行127.0.0.1host的话就没问题。然后确保两个容器能通，host得用redis容器的host

根目录有 .env-example ，是项目的一些配置，copy一份成 .env 然后进行配置

**Comment by Evilran** [comment]
我尝试了在 www/zPhal/ 项目中 cp .env-example .env 的方法，但还是不行，也进入redis容器后redis-cli成功了。

<img width="642" alt="screen shot 2018-12-20 at 00 40 58" src="https://user-images.githubusercontent.com/8848173/50234278-48355580-03f0-11e9-821e-ef56e9d83e17.png">
<img width="584" alt="screen shot 2018-12-20 at 00 41 35" src="https://user-images.githubusercontent.com/8848173/50234281-48cdec00-03f0-11e9-94b9-89c18af90e5f.png">
<img width="286" alt="screen shot 2018-12-20 at 00 42 18" src="https://user-images.githubusercontent.com/8848173/50234283-49668280-03f0-11e9-8cc1-2e7389fc2714.png">

**Comment by goozp** [comment]
容器都是正常运行的啊

应该是配置没加载到，取了默认配置127.0.0.1了。
你composer下载依赖了没？

**Comment by Evilran** [comment]
<img width="453" alt="screen shot 2018-12-21 at 20 13 53" src="https://user-images.githubusercontent.com/8848173/50342184-083fb100-055d-11e9-80da-fc180fa4a37d.png">
重启了docker 还是不行...
配置应该是没问题的啊

**Comment by goozp** [comment]
我重新构建了一遍，重现了你的问题。
不过就是因为没有配置文件导致的，确保一下你有这个文件：
![image](https://user-images.githubusercontent.com/17734933/50359436-b5cfb600-0597-11e9-9b75-051edfd9fec8.png)

**Comment by Evilran** [comment]
这个文件是有的，我觉得也是配置的问题，请问是没加载到吗？
<img width="352" alt="screen shot 2018-12-22 at 21 21 50" src="https://user-images.githubusercontent.com/8848173/50374885-bddb3480-062f-11e9-9858-d93af67613f6.png">

**Comment by goozp** [comment]
docker-compose.yml是怎么写的？
文件权限呢

**Comment by Evilran** [comment]
> cat docker-compose.yml
version: '3.2'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ../app:/data/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../app:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
      build: ./mysql
      ports:
        - "3306:3306"
      volumes:
        - ../data/mysql:/var/lib/mysql:rw
        - ../logs/mysql:/var/lib/mysql-logs:rw
        - ./mysql/conf.d:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: zphaldb
        MYSQL_USER: zphal
        MYSQL_PASSWORD: zphal123
      restart: always
      command: "--character-set-server=utf8"

  redis-db:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data

文件权限应该是没问题的。
直接 docker-compose run --rm -w /data/www/zPhal php-fpm composer update 执行的

**Comment by goozp** [comment]
这个文件没改是吧

那很奇怪。我试了也是可以的，只要配置文件加载到就应该没问题才对。
